CREATE DATABASE ACHEI;
USE ACHEI;
CREATE TABLE IMOVEL(
	IDIMOVEL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TIPO CHAR(2) NOT NULL,
    DORMITORIOS INT NOT NULL,
    BANHEIROS INT NOT NULL,
    SUITES INT NOT NULL,
    VAGASGARAGEM INT NOT NULL,
    AREACONSTRUIDA DOUBLE NOT NULL,
    AREATOTAL DOUBLE NOT NULL,
    VALOR DOUBLE NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(20),
    OBSERVACAO TEXT,
    STATUS VARCHAR(50)
);
CREATE TABLE IMOVELFOTO(
	IDIMOVELFOTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDIMOVEL INT NOT NULL,
    FOTO BLOB NOT NULL,
    FOREIGN KEY(IDIMOVEL) REFERENCES IMOVEL(IDIMOVEL) ON DELETE CASCADE
);
CREATE TABLE CASA(
	IDCASA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDIMOVEL INT NOT NULL,
	LOTE VARCHAR(30) NOT NULL,
    QUADRA VARCHAR(30) NOT NULL,
    FOREIGN KEY(IDIMOVEL) REFERENCES IMOVEL(IDIMOVEL) ON DELETE CASCADE
);
CREATE TABLE APARTAMENTO(
	IDAPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDIMOVEL INT NOT NULL,
	BLOCO VARCHAR(30) NOT NULL,
    ANDAR INT NOT NULL,
    NUMEROAP INT NOT NULL,
    SACADA BOOLEAN NOT NULL,
    FOREIGN KEY(IDIMOVEL) REFERENCES IMOVEL(IDIMOVEL) ON DELETE CASCADE
);
CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    OBSERVACAO TEXT,
    ATIVO BOOLEAN NOT NULL
);
CREATE TABLE USUARIOCONTATO(
	IDUSUARIOCONTATO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IDUSUARIO INT NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    CONTATO VARCHAR(100),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO) ON DELETE CASCADE
);
